### ISSUE TITLE
Create an interface for students to login

### ISSUE THREAD

**Issue by w0rks74710n** [ThomaLa/group-4-9-attendance_tracking_system#15]
Using relevant items from the Guestbook example as your guide, first create an interface for students to login to the Attendance tracking system’s main website

**Comment by ThomaLa** [comment]
Hmm... isn't that already done? Or do you think we should check the student against a list of allowed students, which may be updated by the tutor?
Anyway I think the interface is done (save the diffusion of group details, which should be easy, and later functionalities) and it's the access to it that needs work

**Comment by ThomaLa** [comment]
Actually that's already in Issue #42.. So I think this issue is done
