### ISSUE TITLE
Differentiate between admin, student and troll

### ISSUE THREAD

**Issue by ThomaLa** [ThomaLa/group-4-9-attendance_tracking_system#5]
Any user may log in as student or even admin, it might be useful to at least check the username against a list of authorized persons (or at least pre/suf-fixes), and eventually support passwords, for the example to be realistic

**Comment by aynesh** [comment]
Basically we should integrate security as the next item i guess,

More links:
https://docs.oracle.com/cd/E19644-01/817-5448/dgsecure.html

**Comment by aynesh** [comment]
So i guess we should new classes for Permissions and Roles .... So Roles have multiple permissions ..... And based on user type (student/tutor) we should assign roles to the user.

**Comment by ThomaLa** [comment]
Though in a first step only a permissions class might be useful, roles can just be strings recognized by the constructor of Permission. ?

**Comment by aynesh** [comment]
No i think showing a strong OO structure is important here (Since its ASE class !) .  Code also becomes easier to understand .....

**Comment by aynesh** [comment]
Users -> Roles -> Permissions ? 
We need to connect groups also .....

**Comment by ThomaLa** [comment]
Ok you're probably right :)
And you mean by “connect[ing] groups” that a user should have a field pointing towards its group, instead of just the String field? As long as we ensure the updating of the group remains in O(1), I agree it will make everything easier. I'll take a look at it this evening or tomorrow.

**Comment by aynesh** [comment]
yes User should have a pointer to group or set of group objects ..... Ok let me know how we should proceed.....

**Comment by ThomaLa** [comment]
Shouldn't be too difficult, if you want to take care of it go ahead (I just don't do it know because I'm following a lecture ^^). Should just imply changing Student class and SignInServlet, and ripple effects in group.jsp. But I'm not really sure how to do pointers in java, that's why I rather chose to store an ID ...
Other options would be to keep the current system and just create a function (in Group class or whatever) to retrieve a group, or use IDs more “properly” and make use of Objectify's ```load().type(X.class).ids(...)```

**Comment by aynesh** [comment]
I think the assignments talk only about functionality implementation and design is upto us. . .

**Comment by ThomaLa** [comment]
Weird, Student nor Group can be fetched by ID (eg with ofy().load()....id().now() ), even though that's how we recognize them when we look through the list... Created a branch to work that out, feel free to correct this

**Comment by ThomaLa** [comment]
OK sub-issue solved, implemented and escalated. Student stores an id of its group, fetch it with niceties such as ```hisGroup = ObjectifyService.ofy().cache(false).load().key(Key.create(theCourse, Group.class, thisStudent.group)).now();```.

Remains the creation of Roles/Permissions classes ;)

**Comment by aynesh** [comment]
Hi Thomas should we do hangout / skype for quick sync ?

**Comment by ThomaLa** [comment]
Hmm why not, rather Hangouts and this morning ;) Any question in particular?


2017-11-24 19:46 GMT+01:00 aynesh <notifications@github.com>:
