### ISSUE TITLE
group.jsp is a blob

### ISSUE THREAD

**Issue by ThomaLa** [ThomaLa/group-4-9-attendance_tracking_system#6]
Do you also think it's worth separating it into different pages, according to user status or privilege?

**Comment by aynesh** [comment]
https://docs.oracle.com/javaee/6/tutorial/doc/gjiie.html 
This is a sample, Similarly we can integrate J2EE security features into our project then it becomes way to easy to maintain roles and stuff. Also we can dynamically render jsps based on the roles (Like can hide certain parts of the page)/
